//
//  Currency.swift
//  Budget Planner
//
//  Created by mac on 09/09/25.
//

import Foundation

// MARK: - Model
struct Currency: Identifiable, Hashable {
    let id = UUID()
    let code: String
    let name: String
    let symbol: String
}

// MARK: - Data Source
struct CurrencyData {
    static let allCurrencies: [Currency] = [
        Currency(code: "AED", name: "UAE Dirham", symbol: "د.إ"),
        Currency(code: "AFN", name: "Afghan Afghani", symbol: "؋"),
        Currency(code: "ALL", name: "Albanian Lek", symbol: "L"),
        Currency(code: "AMD", name: "Armenian Dram", symbol: "֏"),
        Currency(code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ"),
        Currency(code: "AOA", name: "Angolan Kwanza", symbol: "Kz"),
        Currency(code: "ARS", name: "Argentina Peso", symbol: "$"),
        Currency(code: "AUD", name: "Australia Dollar", symbol: "$"),
        Currency(code: "AWG", name: "Aruban Florin", symbol: "ƒ"),
        Currency(code: "AZN", name: "Azerbaijan Manat", symbol: "₼"),
        Currency(code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", symbol: "KM"),
        Currency(code: "BBD", name: "Barbados Dollar", symbol: "$"),
        Currency(code: "BDT", name: "Bangladesh Taka", symbol: "৳"),
        Currency(code: "BGN", name: "Bulgaria Lev", symbol: "лв"),
        Currency(code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب"),
        Currency(code: "BIF", name: "Burundi Franc", symbol: "FBu"),
        Currency(code: "BMD", name: "Bermuda Dollar", symbol: "$"),
        Currency(code: "BND", name: "Brunei Darussalam Dollar", symbol: "$"),
        Currency(code: "BOB", name: "Bolivia Boliviano", symbol: "$b"),
        Currency(code: "BRL", name: "Brazil Real", symbol: "R$"),
        Currency(code: "BSD", name: "Bahamas Dollar", symbol: "$"),
        Currency(code: "BTN", name: "Bhutan Ngultrum", symbol: "Nu."),
        Currency(code: "BWP", name: "Botswana Pula", symbol: "P"),
        Currency(code: "BYN", name: "Belarus Ruble", symbol: "Br"),
        Currency(code: "BZD", name: "Belize Dollar", symbol: "BZ$"),
        Currency(code: "CAD", name: "Canada Dollar", symbol: "$"),
        Currency(code: "CDF", name: "Congo/Kinshasa Franc", symbol: "FC"),
        Currency(code: "CHF", name: "Switzerland Franc", symbol: "CHF"),
        Currency(code: "CLP", name: "Chile Peso", symbol: "$"),
        Currency(code: "CNY", name: "China Yuan Renminbi", symbol: "¥"),
        Currency(code: "COP", name: "Colombia Peso", symbol: "$"),
        Currency(code: "CRC", name: "Costa Rica Colon", symbol: "₡"),
        Currency(code: "CUC", name: "Cuba Convertible Peso", symbol: "$"),
        Currency(code: "CUP", name: "Cuba Peso", symbol: "₱"),
        Currency(code: "CVE", name: "Cape Verde Escudo", symbol: "$"),
        Currency(code: "CZK", name: "Czech Republic Koruna", symbol: "Kč"),
        Currency(code: "DJF", name: "Djibouti Franc", symbol: "Fdj"),
        Currency(code: "DKK", name: "Denmark Krone", symbol: "kr"),
        Currency(code: "DOP", name: "Dominican Republic Peso", symbol: "RD$"),
        Currency(code: "DZD", name: "Algeria Dinar", symbol: "دج"),
        Currency(code: "EGP", name: "Egypt Pound", symbol: "£"),
        Currency(code: "ERN", name: "Eritrea Nakfa", symbol: "Nfk"),
        Currency(code: "ETB", name: "Ethiopia Birr", symbol: "Br"),
        Currency(code: "EUR", name: "Euro Member Countries", symbol: "€"),
        Currency(code: "FJD", name: "Fiji Dollar", symbol: "$"),
        Currency(code: "FKP", name: "Falkland Islands Pound", symbol: "£"),
        Currency(code: "GBP", name: "United Kingdom Pound", symbol: "£"),
        Currency(code: "GEL", name: "Georgia Lari", symbol: "₾"),
        Currency(code: "GGP", name: "Guernsey Pound", symbol: "£"),
        Currency(code: "GHS", name: "Ghana Cedi", symbol: "¢"),
        Currency(code: "GIP", name: "Gibraltar Pound", symbol: "£"),
        Currency(code: "GMD", name: "Gambia Dalasi", symbol: "D"),
        Currency(code: "GNF", name: "Guinea Franc", symbol: "GF"),
        Currency(code: "GTQ", name: "Guatemala Quetzal", symbol: "Q"),
        Currency(code: "GYD", name: "Guyana Dollar", symbol: "$"),
        Currency(code: "HKD", name: "Hong Kong Dollar", symbol: "$"),
        Currency(code: "HNL", name: "Honduras Lempira", symbol: "L"),
        Currency(code: "HRK", name: "Croatia Kuna", symbol: "kn"),
        Currency(code: "HTG", name: "Haiti Gourde", symbol: "G"),
        Currency(code: "HUF", name: "Hungary Forint", symbol: "Ft"),
        Currency(code: "IDR", name: "Indonesia Rupiah", symbol: "Rp"),
        Currency(code: "ILS", name: "Israel Shekel", symbol: "₪"),
        Currency(code: "IMP", name: "Isle of Man Pound", symbol: "£"),
        Currency(code: "INR", name: "India Rupee", symbol: "₹"),
        Currency(code: "IQD", name: "Iraq Dinar", symbol: "ع.د"),
        Currency(code: "IRR", name: "Iran Rial", symbol: "﷼"),
        Currency(code: "ISK", name: "Iceland Krona", symbol: "kr"),
        Currency(code: "JEP", name: "Jersey Pound", symbol: "£"),
        Currency(code: "JMD", name: "Jamaica Dollar", symbol: "J$"),
        Currency(code: "JOD", name: "Jordan Dinar", symbol: "JD"),
        Currency(code: "JPY", name: "Japan Yen", symbol: "¥"),
        Currency(code: "KES", name: "Kenya Shilling", symbol: "KSh"),
        Currency(code: "KGS", name: "Kyrgyzstan Som", symbol: "лв"),
        Currency(code: "KHR", name: "Cambodia Riel", symbol: "៛"),
        Currency(code: "KMF", name: "Comoros Franc", symbol: "CF"),
        Currency(code: "KPW", name: "Korea (North) Won", symbol: "₩"),
        Currency(code: "KRW", name: "Korea (South) Won", symbol: "₩"),
        Currency(code: "KWD", name: "Kuwait Dinar", symbol: "KD"),
        Currency(code: "KYD", name: "Cayman Islands Dollar", symbol: "$"),
        Currency(code: "KZT", name: "Kazakhstan Tenge", symbol: "лв"),
        Currency(code: "LAK", name: "Laos Kip", symbol: "₭"),
        Currency(code: "LBP", name: "Lebanon Pound", symbol: "£"),
        Currency(code: "LKR", name: "Sri Lanka Rupee", symbol: "₨"),
        Currency(code: "LRD", name: "Liberia Dollar", symbol: "$"),
        Currency(code: "LSL", name: "Lesotho Loti", symbol: "M"),
        Currency(code: "LYD", name: "Libya Dinar", symbol: "LD"),
        Currency(code: "MAD", name: "Morocco Dirham", symbol: "MAD"),
        Currency(code: "MDL", name: "Moldova Leu", symbol: "lei"),
        Currency(code: "MGA", name: "Madagascar Ariary", symbol: "Ar"),
        Currency(code: "MKD", name: "Macedonia Denar", symbol: "ден"),
        Currency(code: "MMK", name: "Myanmar Kyat", symbol: "K"),
        Currency(code: "MNT", name: "Mongolia Tughrik", symbol: "₮"),
        Currency(code: "MOP", name: "Macau Pataca", symbol: "MOP$"),
        Currency(code: "MRU", name: "Mauritania Ouguiya", symbol: "UM"),
        Currency(code: "MUR", name: "Mauritius Rupee", symbol: "₨"),
        Currency(code: "MVR", name: "Maldives Rufiyaa", symbol: "Rf"),
        Currency(code: "MWK", name: "Malawi Kwacha", symbol: "MK"),
        Currency(code: "MXN", name: "Mexico Peso", symbol: "$"),
        Currency(code: "MYR", name: "Malaysia Ringgit", symbol: "RM"),
        Currency(code: "MZN", name: "Mozambique Metical", symbol: "MT"),
        Currency(code: "NAD", name: "Namibia Dollar", symbol: "$"),
        Currency(code: "NGN", name: "Nigeria Naira", symbol: "₦"),
        Currency(code: "NIO", name: "Nicaragua Cordoba", symbol: "C$"),
        Currency(code: "NOK", name: "Norway Krone", symbol: "kr"),
        Currency(code: "NPR", name: "Nepal Rupee", symbol: "₨"),
        Currency(code: "NZD", name: "New Zealand Dollar", symbol: "$"),
        Currency(code: "OMR", name: "Oman Rial", symbol: "﷼"),
        Currency(code: "PAB", name: "Panama Balboa", symbol: "B/."),
        Currency(code: "PEN", name: "Peru Nuevo Sol", symbol: "S/."),
        Currency(code: "PGK", name: "Papua New Guinea Kina", symbol: "K"),
        Currency(code: "PHP", name: "Philippines Peso", symbol: "₱"),
        Currency(code: "PKR", name: "Pakistan Rupee", symbol: "₨"),
        Currency(code: "PLN", name: "Poland Zloty", symbol: "zł"),
        Currency(code: "PYG", name: "Paraguay Guarani", symbol: "Gs"),
        Currency(code: "QAR", name: "Qatar Riyal", symbol: "﷼"),
        Currency(code: "RON", name: "Romania New Leu", symbol: "lei"),
        Currency(code: "RSD", name: "Serbia Dinar", symbol: "Дин."),
        Currency(code: "RUB", name: "Russia Ruble", symbol: "₽"),
        Currency(code: "RWF", name: "Rwanda Franc", symbol: "R₣"),
        Currency(code: "SAR", name: "Saudi Arabia Riyal", symbol: "﷼"),
        Currency(code: "SBD", name: "Solomon Islands Dollar", symbol: "$"),
        Currency(code: "SCR", name: "Seychelles Rupee", symbol: "₨"),
        Currency(code: "SDG", name: "Sudan Pound", symbol: "ج.س."),
        Currency(code: "SEK", name: "Sweden Krona", symbol: "kr"),
        Currency(code: "SGD", name: "Singapore Dollar", symbol: "$"),
        Currency(code: "SHP", name: "Saint Helena Pound", symbol: "£"),
        Currency(code: "SLE", name: "Sierra Leone Leone", symbol: "Le"),
        Currency(code: "SOS", name: "Somalia Shilling", symbol: "S"),
        Currency(code: "SRD", name: "Suriname Dollar", symbol: "$"),
        Currency(code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db"),
        Currency(code: "SVC", name: "El Salvador Colon", symbol: "$"),
        Currency(code: "SYP", name: "Syria Pound", symbol: "£"),
        Currency(code: "SZL", name: "Swaziland Lilangeni", symbol: "E"),
        Currency(code: "THB", name: "Thailand Baht", symbol: "฿"),
        Currency(code: "TJS", name: "Tajikistan Somoni", symbol: "SM"),
        Currency(code: "TMT", name: "Turkmenistan Manat", symbol: "T"),
        Currency(code: "TND", name: "Tunisia Dinar", symbol: "د.ت"),
        Currency(code: "TOP", name: "Tonga Pa'anga", symbol: "T$"),
        Currency(code: "TRY", name: "Turkey Lira", symbol: "₺"),
        Currency(code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$"),
        Currency(code: "TVD", name: "Tuvalu Dollar", symbol: "$"),
        Currency(code: "TWD", name: "Taiwan New Dollar", symbol: "NT$"),
        Currency(code: "TZS", name: "Tanzania Shilling", symbol: "TSh"),
        Currency(code: "UAH", name: "Ukraine Hryvnia", symbol: "₴"),
        Currency(code: "UGX", name: "Uganda Shilling", symbol: "USh"),
        Currency(code: "USD", name: "United States Dollar", symbol: "$"),
        Currency(code: "UYU", name: "Uruguay Peso", symbol: "$U"),
        Currency(code: "UZS", name: "Uzbekistan Som", symbol: "лв"),
        Currency(code: "VED", name: "Venezuela Bolívar", symbol: "Bs"),
        Currency(code: "VND", name: "Viet Nam Dong", symbol: "₫"),
        Currency(code: "VUV", name: "Vanuatu Vatu", symbol: "VT"),
        Currency(code: "WST", name: "Samoa Tala", symbol: "WS$"),
        Currency(code: "XAF", name: "Communauté Financière Africaine (BEAC) CFA Franc", symbol: "FCFA"),
        Currency(code: "XCD", name: "East Caribbean Dollar", symbol: "$"),
        Currency(code: "XDR", name: "International Monetary Fund (IMF) Special Drawing Rights", symbol: "XDR"),
        Currency(code: "XOF", name: "Communauté Financière Africaine (BCEAO) Franc", symbol: "CFA"),
        Currency(code: "XPF", name: "Comptoirs Français du Pacifique (CFP) Franc", symbol: "₣"),
        Currency(code: "YER", name: "Yemen Rial", symbol: "﷼"),
        Currency(code: "ZAR", name: "South Africa Rand", symbol: "R"),
        Currency(code: "ZMW", name: "Zambia Kwacha", symbol: "ZK"),
        Currency(code: "ZWL", name: "Zimbabwe Dollar", symbol: "Z$")
    ]
}
